apiVersion: batch/v1
kind: Job
metadata:
  name: data-aggregator
spec:
  template:
    spec:
      containers:
        - name: aggregator
          image: gprmax-simulation:latest
          imagePullPolicy: Never
          command: ["python3", "Python/aggregator.py"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
      restartPolicy: Never
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: gprmax-pvc