apiVersion: batch/v1
kind: Job
metadata:
  name: gprmax-aggregator
spec:
  template:
    spec:
      containers:
      - name: aggregator
        image: pratiktech28/aggregator:latest
        command: ["python3", "aggregator.py"] 
        volumeMounts:
        - name: data-storage
          mountPath: /data
      restartPolicy: OnFailure
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: gprmax-pvc
  backoffLimit: 4
  activeDeadlineSeconds: 