apiVersion: v1
kind: PersistentVolume
metadata:
  name: gprmax-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/gprmax" 