name: gprMax Automation Phase 3

on:
  push:
    branches: [ fix/automation-actions ]

jobs:
  full-simulation-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Kubernetes (Kind)
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.20.0"

      - name: Build & Load Image
        run: |
          docker build -t gprmax-simulation:latest -f Docker/Dockerfile .
          kind load docker-image gprmax-simulation:latest --name kind

      - name: Deploy 10 Pods & Aggregator
        run: |
          # Maan raha hoon ki teri files 'k8s/' folder mein hain
          kubectl apply -f Kubernetes/
          
      - name: Wait for Completion
        run: |
          echo "Waiting for simulations to finish..."
          sleep 180
          kubectl get pods

      - name: Extract Artifacts from /app
        run: |
          mkdir -p results_temp
          
          sleep 5 
          
          POD_NAME=$(kubectl get pods -l job-name=data-aggregator --field-selector=status.phase=Running -o jsonpath='{.items[0].metadata.name}')
          
          if [ -z "$POD_NAME" ]; then
            echo 
            exit 1
          fi
          
          echo "✅ Found Pod: $POD_NAME"
          kubectl cp $POD_NAME:/app/simulation_registry.db ./results_temp/simulation_registry.db
          kubectl cp $POD_NAME:/app/final_summary.csv ./results_temp/final_summary.csv
          
          echo "🚀 Artifacts extracted to results_temp/"
          ls -la results_temp/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gprMax-Simulation-Results
          path: results_temp/