name: gprMax-Kuber-Automation

on:
  push:
    branches: [ fix/automation-actions ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: gprmax-automation

      - name: Build Simulation Image
        run: |
          docker build -t gprmax-simulation:latest -f Docker/Dockerfile .

      - name: Load Image and Set Context
        run: |
          kind export kubeconfig --name gprmax-automation
          
          kind load docker-image gprmax-simulation:latest --name gprmax-automation
          
          kubectl cluster-info
          docker exec gprmax-automation-control-plane crictl images | grep gprmax

      - name: Deploy gprMax
        run: |
          kubectl apply -f Kubernetes/
          echo "Waiting for Physics Simulation to complete..."
          sleep 30
      - name: Force Extract Artifacts
        run: |
          mkdir -p results_temp
          POD_NAME=$(kubectl get pods -l job-name=data-aggregator --no-headers -o custom-columns=":metadata.name" | head -n 1)
          
          echo "Targeting Pod: $POD_NAME"
          
          kubectl cp $POD_NAME:/data/simulation_registry.db ./results_temp/simulation_registry.db
          kubectl cp $POD_NAME:/data/final_summary.csv ./results_temp/final_summary.csv
          

          ls -lh results_temp/

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: GSoC-Final-Artifacts
          path: results_temp/